branches:
  only:
  - master
language: python
python:
- 2.7
install:
- pip install -r requirements.txt --use-mirrors
script:
- make html
notifications:
  email:
    on_success: always
    on_failure: always
after_success: bash deploy.sh
after_script:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
env:
  global:
    secure: Qjx1/Wpr2dRkzs5Z3i8mnAfHc+qC6ELWFdSgtwTFc8PY2XP820bVGmBC3BuabIaKLiJpYV4tLGoWTExRNbMC4ScECOFoVUcL1kBVEJ6JjS7tgHBp/74zQpR9x8cfQxJ0Rq4EHoSPwWs/M6hJxq2aMzBWG9v1XBzlAh9g8wZo14Z/YwiBpqCn2bUPVDjD3fFC5BudVd3dkkpMCrpHIvzMJVYrXwfQrAMthBX3Yj8M/C1/aGsvvRn2FBWeppzHaiN0aXjoxvWWErLIyju/i1nHDoaJkQxY/nZ4lRUoc8bdYvdoHKykp7lYLclrzzMKqW6V4bah07/CsseSlISaDB8SP18szfR856I/hxRyNkIMzhAt617b439x5xP5LocaZancCq13+tOoIhmsdMNSAvwSX3Wfv6XJd71LQryr1iD7i8yKkdAo0uenhrD3WtudNJ7oIgaKjyHCwehZ1eoDeBzJBkgpvN/5OChrNxeV5ocXGpGBZqe5v7cDtVW0wr+poZCm4LP/knsXWtzhP2jr/bnbujQ2sqX/B/ZUemLp1P0a3at3CgUOgruHRro1Z28Jvvl1dZwGq60O6jNBn3nmnfCqK0RIL9FzLtSud+4nOoQLkFUrbyuxvtYi+80bYThjRFHobSrYQvKAGZKpxwhZacKXHKrMl08+qjVVXzFPL6ecFG0=
